-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\rev_completo_8bits\reverberador_completo_8b_pkg.vhd
-- Created: 2021-02-21 17:09:08
-- 
-- Generated by MATLAB 9.4 and HDL Coder 3.12
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE reverberador_completo_8b_pkg IS
  TYPE vector_of_signed8 IS ARRAY (NATURAL RANGE <>) OF signed(7 DOWNTO 0);
END reverberador_completo_8b_pkg;

