-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\rev_completo_with_audio_backup\reverberador_completo_pkg.vhd
-- Created: 2021-02-20 19:49:52
-- 
-- Generated by MATLAB 9.4 and HDL Coder 3.12
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE reverberador_completo_pkg IS
  TYPE vector_of_signed16 IS ARRAY (NATURAL RANGE <>) OF signed(15 DOWNTO 0);
END reverberador_completo_pkg;

