-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\flanger_short\lfo_multiplier.vhd
-- Created: 2021-02-20 22:34:20
-- 
-- Generated by MATLAB 9.4 and HDL Coder 3.12
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 2.26757e-05
-- Target subsystem base rate: 2.26757e-05
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: lfo_multiplier
-- Source Path: lfo_multiplier
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY lfo_multiplier IS
  PORT( In1                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        Out1                              :   OUT   std_logic_vector(15 DOWNTO 0)  -- int16
        );
END lfo_multiplier;


ARCHITECTURE rtl OF lfo_multiplier IS

  -- Signals
  SIGNAL Constant2_out1                   : signed(15 DOWNTO 0);  -- sfix16_En11
  SIGNAL In1_signed                       : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Product_out1                     : signed(31 DOWNTO 0);  -- sfix32_En25
  SIGNAL Constant1_out1                   : signed(15 DOWNTO 0);  -- sfix16_En10
  SIGNAL Sum2_add_cast                    : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL Sum2_add_cast_1                  : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL Sum2_out1                        : signed(15 DOWNTO 0);  -- int16

BEGIN
  Constant2_out1 <= to_signed(16#7800#, 16);

  In1_signed <= signed(In1);

  Product_out1 <= Constant2_out1 * In1_signed;

  Constant1_out1 <= to_signed(16#7800#, 16);

  Sum2_add_cast <= (resize(Product_out1(31 DOWNTO 25), 16)) + ('0' & (Product_out1(24) OR Product_out1(23) OR Product_out1(22) OR Product_out1(21) OR Product_out1(20) OR Product_out1(19) OR Product_out1(18) OR Product_out1(17) OR Product_out1(16) OR Product_out1(15) OR Product_out1(14) OR Product_out1(13) OR Product_out1(12) OR Product_out1(11) OR Product_out1(10) OR Product_out1(9) OR Product_out1(8) OR Product_out1(7) OR Product_out1(6) OR Product_out1(5) OR Product_out1(4) OR Product_out1(3) OR Product_out1(2) OR Product_out1(1) OR Product_out1(0)));
  Sum2_add_cast_1 <= (resize(Constant1_out1(15 DOWNTO 10), 16)) + ('0' & (Constant1_out1(9) OR Constant1_out1(8) OR Constant1_out1(7) OR Constant1_out1(6) OR Constant1_out1(5) OR Constant1_out1(4) OR Constant1_out1(3) OR Constant1_out1(2) OR Constant1_out1(1) OR Constant1_out1(0)));
  Sum2_out1 <= Sum2_add_cast + Sum2_add_cast_1;

  Out1 <= std_logic_vector(Sum2_out1);

END rtl;

