-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\echo_8b\echo.vhd
-- Created: 2021-02-21 18:01:14
-- 
-- Generated by MATLAB 9.4 and HDL Coder 3.12
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 2.26757e-05
-- Target subsystem base rate: 2.26757e-05
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        2.26757e-05
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out1                          ce_out        2.26757e-05
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: echo
-- Source Path: echo_8b/echo
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.echo_pkg.ALL;

ENTITY echo IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        In1                               :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        ce_out                            :   OUT   std_logic;
        Out1                              :   OUT   std_logic_vector(7 DOWNTO 0)  -- int8
        );
END echo;


ARCHITECTURE rtl OF echo IS

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL In1_signed                       : signed(7 DOWNTO 0);  -- int8
  SIGNAL Delay_reg                        : vector_of_signed8(0 TO 5999);  -- sfix8 [6000]
  SIGNAL Delay_out1                       : signed(7 DOWNTO 0);  -- int8
  SIGNAL attenuation_cast                 : signed(15 DOWNTO 0);  -- sfix16_En7
  SIGNAL attenuation_out1                 : signed(7 DOWNTO 0);  -- int8
  SIGNAL Sum_out1                         : signed(7 DOWNTO 0);  -- int8

BEGIN
  In1_signed <= signed(In1);

  enb <= clk_enable;

  Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay_reg <= (OTHERS => to_signed(16#00#, 8));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay_reg(0) <= In1_signed;
        Delay_reg(1 TO 5999) <= Delay_reg(0 TO 5998);
      END IF;
    END IF;
  END PROCESS Delay_process;

  Delay_out1 <= Delay_reg(5999);

  attenuation_cast <= resize(Delay_out1 & '0' & '0' & '0' & '0' & '0' & '0', 16);
  attenuation_out1 <= attenuation_cast(14 DOWNTO 7) + ('0' & (attenuation_cast(6) AND (( NOT attenuation_cast(15)) OR (attenuation_cast(5) OR attenuation_cast(4) OR attenuation_cast(3) OR attenuation_cast(2) OR attenuation_cast(1) OR attenuation_cast(0)))));

  Sum_out1 <= In1_signed + attenuation_out1;

  Out1 <= std_logic_vector(Sum_out1);

  ce_out <= clk_enable;

END rtl;

