-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\delay\delay_effect_200ms_pkg.vhd
-- Created: 2021-02-19 23:03:12
-- 
-- Generated by MATLAB 9.4 and HDL Coder 3.12
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE delay_effect_200ms_pkg IS
  TYPE vector_of_signed16 IS ARRAY (NATURAL RANGE <>) OF signed(15 DOWNTO 0);
END delay_effect_200ms_pkg;

