-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\delay\delay_effect_200ms.vhd
-- Created: 2021-02-19 23:12:35
-- 
-- Generated by MATLAB 9.4 and HDL Coder 3.12
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 2.26757e-05
-- Target subsystem base rate: 2.26757e-05
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        2.26757e-05
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out1                          ce_out        2.26757e-05
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: delay_effect_200ms
-- Source Path: delay/delay_effect_200ms
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.delay_effect_200ms_pkg.ALL;

ENTITY delay_effect_200ms IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        In1                               :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        ce_out                            :   OUT   std_logic;
        Out1                              :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END delay_effect_200ms;


ARCHITECTURE rtl OF delay_effect_200ms IS

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL In1_unsigned                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Delay_reg                        : vector_of_unsigned8(0 TO 8819);  -- ufix8 [8820]
  SIGNAL Delay_out1                       : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL attenuation_mul_temp             : unsigned(15 DOWNTO 0);  -- ufix16_En9
  SIGNAL attenuation_out1                 : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Sum_out1                         : unsigned(7 DOWNTO 0);  -- uint8

BEGIN
  In1_unsigned <= unsigned(In1);

  enb <= clk_enable;

  Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay_reg <= (OTHERS => to_unsigned(16#00#, 8));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay_reg(0) <= In1_unsigned;
        Delay_reg(1 TO 8819) <= Delay_reg(0 TO 8818);
      END IF;
    END IF;
  END PROCESS Delay_process;

  Delay_out1 <= Delay_reg(8819);

  attenuation_mul_temp <= to_unsigned(16#9A#, 8) * Delay_out1;
  attenuation_out1 <= (resize(attenuation_mul_temp(15 DOWNTO 9), 8)) + ('0' & attenuation_mul_temp(8));

  Sum_out1 <= In1_unsigned + attenuation_out1;

  Out1 <= std_logic_vector(Sum_out1);

  ce_out <= clk_enable;

END rtl;

