-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\delay\delay_effect_200ms.vhd
-- Created: 2021-02-19 23:03:12
-- 
-- Generated by MATLAB 9.4 and HDL Coder 3.12
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 2.26757e-05
-- Target subsystem base rate: 2.26757e-05
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        2.26757e-05
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out1                          ce_out        2.26757e-05
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: delay_effect_200ms
-- Source Path: delay/delay_effect_200ms
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.delay_effect_200ms_pkg.ALL;

ENTITY delay_effect_200ms IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        In1                               :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        ce_out                            :   OUT   std_logic;
        Out1                              :   OUT   std_logic_vector(15 DOWNTO 0)  -- int16
        );
END delay_effect_200ms;


ARCHITECTURE rtl OF delay_effect_200ms IS

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL In1_signed                       : signed(15 DOWNTO 0);  -- int16
  SIGNAL Delay_reg                        : vector_of_signed16(0 TO 8819);  -- sfix16 [8820]
  SIGNAL Delay_out1                       : signed(15 DOWNTO 0);  -- int16
  SIGNAL attenuation_mul_temp             : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL attenuation_out1                 : signed(15 DOWNTO 0);  -- int16
  SIGNAL Sum_out1                         : signed(15 DOWNTO 0);  -- int16

BEGIN
  In1_signed <= signed(In1);

  enb <= clk_enable;

  Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay_reg <= (OTHERS => to_signed(16#0000#, 16));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay_reg(0) <= In1_signed;
        Delay_reg(1 TO 8819) <= Delay_reg(0 TO 8818);
      END IF;
    END IF;
  END PROCESS Delay_process;

  Delay_out1 <= Delay_reg(8819);

  attenuation_mul_temp <= to_signed(16#4CCD#, 16) * Delay_out1;
  attenuation_out1 <= attenuation_mul_temp(31 DOWNTO 16) + ('0' & (attenuation_mul_temp(15) AND (( NOT attenuation_mul_temp(31)) OR (attenuation_mul_temp(14) OR attenuation_mul_temp(13) OR attenuation_mul_temp(12) OR attenuation_mul_temp(11) OR attenuation_mul_temp(10) OR attenuation_mul_temp(9) OR attenuation_mul_temp(8) OR attenuation_mul_temp(7) OR attenuation_mul_temp(6) OR attenuation_mul_temp(5) OR attenuation_mul_temp(4) OR attenuation_mul_temp(3) OR attenuation_mul_temp(2) OR attenuation_mul_temp(1) OR attenuation_mul_temp(0)))));

  Sum_out1 <= In1_signed + attenuation_out1;

  Out1 <= std_logic_vector(Sum_out1);

  ce_out <= clk_enable;

END rtl;

