-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\delay\echo_pkg.vhd
-- Created: 2021-02-21 16:02:27
-- 
-- Generated by MATLAB 9.4 and HDL Coder 3.12
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE echo_pkg IS
  TYPE vector_of_signed16 IS ARRAY (NATURAL RANGE <>) OF signed(15 DOWNTO 0);
END echo_pkg;

